(define (domain household)
  (:requirements :strips :typing)
  (:types agent object hand location)
  (:predicates
    (found ?x - object)
    (holding ?a - agent ?x - object)
    (ontable ?x - object)
    (clean ?x - object)
    (handempty ?h - hand)
    (open ?x - object)
    (closed ?x - object)
    (sliced ?x - object)
    (on ?x - object ?y - location)
    (powered ?x - object)
    (goal-achieved)
    (done)
    (openable ?x - object)
    (sliceable ?x - object)
    (switchable ?x - object)
  )
  (:action done
    :parameters ()
    :precondition (goal-achieved)
    :effect (done)
  )
  (:action find
    :parameters (?a - agent ?x - object)
    :precondition (not (found ?x))
    :effect (found ?x)
  )
  (:action pick-up
    :parameters (?a - agent ?h - hand ?x - object ?l - location)
    :precondition (and (found ?x) (on ?x ?l) (handempty ?h))
    :effect (and (holding ?a ?x) (not (on ?x ?l)) (not (handempty ?h)))
  )
  (:action put-down
    :parameters (?a - agent ?h - hand ?x - object ?l - location)
    :precondition (holding ?a ?x)
    :effect (and (on ?x ?l) (handempty ?h) (not (holding ?a ?x)))
  )
  (:action open
    :parameters (?a - agent ?x - object)
    :precondition (and (closed ?x) (openable ?x))
    :effect (and (open ?x) (not (closed ?x)))
  )
  (:action close
    :parameters (?a - agent ?x - object)
    :precondition (and (open ?x) (openable ?x))
    :effect (and (closed ?x) (not (open ?x)))
  )
  (:action slice
    :parameters (?a - agent ?x - object)
    :precondition (and (not (sliced ?x)) (sliceable ?x))
    :effect (sliced ?x)
  )
  (:action turn-on
    :parameters (?a - agent ?x - object)
    :precondition (and (switchable ?x) (not (powered ?x)))
    :effect (powered ?x)
  )
  (:action turn-off
    :parameters (?a - agent ?x - object)
    :precondition (and (switchable ?x) (powered ?x))
    :effect (not (powered ?x))
  )
)
